### ISSUE TITLE
Comment for Assighment1

### ISSUE THREAD

**Issue by Tobetch** [nobeno/Java_RaiseTech02#1]
# helloWorld
- greetingは一文でかけそうですね

# addOneToTen
- 繰り返しのintの初期値は1でもいいですが、特に意図がなければ0でいいと思います（慣例）
- ↑こちらに合わせて継続条件式（i <= 10の部分）も

# dayOfWeek
とくにないですね

# judZeroOrOne
- judZeroOrOneメソッド自体に引数をもたせるようにしてみてください

# arrayTest
- 「String List[]」は"String型の**配列**"となります。「Java List ArrayList 使い方」あたりを調べて、"String型の**List**"を作りましょう。使い方はMapと似ています。

**Comment by q-tobe** [comment]
> judZeroOrOne

jud => judge がいいですね
省略しすぎるとわからなくなりますので
